### ISSUE TITLE
[Error] Unable to read: NativeBuffer

### ISSUE THREAD

**Issue by dmorawetz** [enricostara/telegram-mt-node#11]
I use telegram.link and when I call client.createAuthKey I get an error where the StackTrace shows an error (from the title) net.RpcChannel.

**Comment by enricostara** [comment]
A bit of context? :)

**Comment by dmorawetz** [comment]
You can read my code here: https://github.com/Morosko/atom-telegram/blob/master/lib/atom-telegram.coffee
Line 62 ;)

**Edit:** I have to add, that the error only occurs sometimes, so I'm not sure if it's a problem of the API or if it occurs because of internet connection errors or somethin similar.
