### ISSUE TITLE
Why "var auth = require('lib/auth'); Cannot find declaration to go to.", after I download code?

### ISSUE THREAD

**Issue by yanyanJing** [enricostara/telegram-mt-node#2]
As title, I git clone code and prepare env.  But when I want to run auth-key.test.js it showed

/usr/local/bin/node auth-key.test.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/lib/auth'

**Comment by enricostara** [comment]
In order to execute all the unit-test you can use:
`npm test`

but if you want to run a single test, you have to use mocha and run the unit-test with the relative path,
as following:
`./node_modules/.bin/mocha test/auth/auth-key.test.js`
