### ISSUE TITLE
Unable to retrieve a Type by Name [api.type.User]

### ISSUE THREAD

**Issue by badoualy** [enricostara/telegram-mt-node#5]
Hi,

I was able to update my username simply by adding the following function in a new module (like auth) 
```javascript
Account.prototype.updateUsername = function (username, callback) {
    utility.callService(api.service.account.updateUsername, this.client, this.client._channel, callback, arguments);
};
```

But, when I do the same thing for Message, to get the conversations, with getDialogs
```javascript
Messages.prototype.getDialogs = function (offset, max_id, limit, callback) {
    utility.callService(api.service.messages.getDialogs, this.client, this.client._channel, callback, arguments);
};
```

I get the following 
```
Error: Unable to retrieve a Type by Name [api.type.User]
    at Function.requireTypeByName (node_modules\telegram-tl-node\lib\builder\constructor-builder.js:358:15)
    at Object.requireTypeByName (node_modules\telegram-tl-node\lib\builder\type-builder.js:126:31)
    at TypeVector.manageType (node_modules\telegram-tl-node\lib\type-vector.js:50:23)
    at new TypeVector (node_modules\telegram-tl-node\lib\type-vector.js:34:16)
    at deserialize (eval at createConstructor (node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:31), <anonymous>:63:14)
    at deserialize (eval at createConstructor (node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:30:79)
    at deserialize (eval at createConstructor (node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:33:79)
    at deserialize (eval at createConstructor (node_modules\telegram-tl-node\lib\builder\constructor-builder.js:115:27), <anonymous>:29:80)
```

**Comment by badoualy** [comment]
Pretty sure the error comes from the fact we don't have a predicate "user" in the api tl schema, instead we have multiple constructor userEmpty, userSelf, userContact, etc, but getDialogs still returns a Vector<User>, but the program can't handle that, probably need to create a type-user manually, with all the data, and make the other subtype inherit this one ?

What do you think?

**Comment by enricostara** [comment]
It is a well known problem with the polyformic type deserialization by Vector.. I'm working on the Gzip response management in getContacts() and then I will fix it! :)

**Comment by badoualy** [comment]
Ok sweet, sorry to bother you with that but do you have an estimated amount of time until a fix is available ?

**Comment by enricostara** [comment]
asap, this week ;)

**Comment by badoualy** [comment]
Starting to understand more your code, am I right assuming we need to use the "id" field to retrieve to type instead of the string type field ?
And from what I saw, the id is a transformation of the value in the tlschema:
```javascript
function buildIdentity() {
    var typeId = this.tlSchema.id;
    if (this.tlSchema.id) {
        var buffer = new Buffer(4);
        buffer.writeUInt32LE(this.tlSchema.id, 0, true);
        typeId = buffer.toString('hex'); // Here the id we need to compare in the response
    }
```

**Comment by badoualy** [comment]
Tried on my side to fix the problem, I thought we had the items typeId in the buffer and use a new ```retrieveTypeById``` method, looks like I was wrong, 
any progress on your side ? :)

**Comment by badoualy** [comment]
Managed to retrieve the user list for getDialogs ! Will do a pull request when I have something clean perfectly working, still have some check to do.

I just made a small change in the type retrieving process : if retrieveTypeByName fails, i catch the exception, and when parsing an item in read"Type" method, I read the buffer to get the id.

**Comment by enricostara** [comment]
Yesterday I just fixed this issue, but I pushed it only now. (I was without internet connection)
Now the vector class uses the requiredTypeByBuffer method already available.
Thanks anyway for your work!

**Comment by badoualy** [comment]
Ahahah damn ! Good job ! Just need to fix the gzip issue and this lib will be operational ! ;)
