### ISSUE TITLE
Error deserializing GZip

### ISSUE THREAD

**Issue by badoualy** [enricostara/telegram-mt-node#7]
For every gzip response I get an error :
```
[INFO] Mon, 06 Jul 2015 11:32:38 GMT  mtproto.type.Gzip_packed end > this._buffer.length 1170 952
[WARN] Mon, 06 Jul 2015 11:32:38 GMT  message.EncryptedMessage Unable to decrypt the message, the authKey ids do not match!
[ERROR] Mon, 06 Jul 2015 11:32:38 GMT  net.RpcChannel Unable to deserialize response 1ff1af6482ccce1a58231aaae......
 from mtproto.type.Msgs_ack due to Error: Unable to decrypt the message, the authKey ids do not match!
    at EncryptedMessage.deserialize (C:\Users\...\node_modules\telegram.link\node_modules\telegram-mt-node\lib\message\encrypted-message.js:135:15)
    at EncryptedRpcChannel._deserializeResponse (C:\Users\...\node_modules\telegram.link\node_modules\telegram-mt-node\lib\net\encrypted-rpc-channel.js:206:99)
    at C:\Users\....\node_modules\telegram.link\node_modules\telegram-mt-node\lib\net\rpc-channel.js:64:35
    at Socket.onData (C:\Users\...\node_modules\telegram.link\node_modules\telegram-mt-node\lib\net\tcp-connection.js:143:13)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20) 
```

Happens every time with getContact, sometimes with getDialogs if requesting too much results.
If you have some clue I can try to fix it

Edit: In fact it is working sometimes with DialogSlice

Edit2: This seems to always happen when the response is composed by at least 4 messages.
Below 4 messages, no problem

**Comment by badoualy** [comment]
@enricostara any idea how this can be fixed? I tried to dig a bit, but didn't find anything

**Comment by badoualy** [comment]
Any update ?

**Comment by enricostara** [comment]
therefore could be a problem with long responses.. may you check for yourself if all the data are fetched from the server ?

**Comment by badoualy** [comment]
The error is indeed with long responses, from what I saw we get multiple blocks, and from a certain point, the blocks can't be deserialized. I'm pretty sure we get all the data, for example with getRecentChats, when having a limit of 3 or 4 it's ok, then with 5 it'll start being an issue. And the difference in the amount of data received seems to be coherent.

**Comment by enricostara** [comment]
Could you isolate the problem? we need to know if it's a issue with:
- HttpConnection class (http node library wrong use/implementation?)
- gunzip method: for instance, you could try to change zip library
I'll happy to merge the fix :)

**Comment by badoualy** [comment]
Already tried, without success sadly
I think this issue is not with the gzip library since the error is with the auth key, for the first block no issue, but from some point, the authKey is wrong

But from the logs, this one could be only a side effect of the length error : the first line of the provided log

**Comment by enricostara** [comment]
Therefore could you try using TCP instead? (adding the `connectionType: 'TCP'` app property when you create the client)

**Comment by badoualy** [comment]
Oh, didn't precise my bad, already tried using tcp and http

**Comment by enricostara** [comment]
I fixed the problem on TCP.. :)
tomorrow I try to fix also on HTTP
I will share the fixes asap!

**Comment by badoualy** [comment]
Awesome man !
Can you explain quickly what was the issue please ? I couldn't even figures that out ! :)

**Comment by enricostara** [comment]
It did not fetched all the data and tried to deserialize only with the first chunk

**Comment by enricostara** [comment]
It should be fixed now!
